config/routes.rb
Rails.application.routes.draw do

  get 'events/index'
  root 'events#index'

  get 'events/list', to: 'events#list'

  devise_for :users
  resources :events

end

app/models/events.rb
class Events < ActiveRecord::Base
  def change
    create_table :events do |t|
      t.event_name :string
      t.event_data :datetime
      t.user :string
      t.period :integer

      t.timestamps
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Setup accessible (or protected) attributes for your model



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
require 'date'
require 'time'


class EventsController < ApplicationController
  def new
  end

  def create
    @events = Events.new(events_params)

    @events.save
    redirect_to '/'
  end

  def edit
    @events = Events.find(params[:id])
  end

  def show
    @events = Events.find(params[:id])
  end

  def index
    @events = Events.all

  end

  def update
    @event = Events.find(params[:id])

    if @event.update(events_params)
      redirect_to '/'
    else
      render 'edit'
    end
  end

  def destroy
    @event = Events.find(params[:id])

    @event.delete
    redirect_to '/'
  end

  def list
    cal_start  = DateTime.parse(params['start'])
    cal_end  = DateTime.parse(params['end'])

    if params['all_events'] == 'true'
      @events = Events.all
    else
      @events = Events.where(:user => current_user.to_param)
    end
    events = []
    @events.each { |event|
      i = cal_end - (event.event_data.iso8601).to_date
      current = (event.event_data.iso8601).to_datetime
      if event.period ==1
        if i>0
          z=1
          while  z <= i.to_i do
            events << {:id => event.id, :title => event.event_name, :start => "#{current + z}", :end => "#{current + z}", :allDay => false}
            z+=1
          end
        end
      elsif  event.period == 2
        if i.to_i> 7
          we = i.to_i/7
          x = 1
          while x <= we

            events << {:id => event.id, :title => event.event_name, :start => "#{current + x.week}", :end => "#{current + x.week}", :allDay => false}
            x+=1
          end
        end
      elsif  event.period == 3
        if i.to_i> 30
          mon = i.to_i/30
          x = 1
          while x <= mon
            events << {:id => event.id, :title => event.event_name, :start => "#{current + x.month}", :end => "#{current + x.month}", :allDay => false}
            x+=1
          end
        end
      elsif  event.period == 4
          if i.to_i> 365
            ya = i.to_i/365
            x = 1
            while x <= ya
              current = (event.event_data.iso8601).to_date
              events << {:id => event.id, :title => event.event_name, :start => "#{current + x.year}", :end => "#{current + x.year}", :allDay => false}
              x+=1
            end
        end
      end
      events << {:id => event.id, :title => event.event_name, :start => "#{event.event_data.iso8601}", :end => "#{event.event_data.iso8601}", :allDay => false}
    }


    render :text => events.to_json
  end

  private
  def events_params
    params.require(:events).permit(:event_name, :event_data, :user, :period)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<span style="padding:0px 10px;"></span>
<div class="row">
  <div class="col-xs-6 col-sm-4"></div>
  <div class="col-xs-6 col-sm-4">

<h1>Изменить задание</h1>

<%= form_for :events, url: event_path(@events), method: :patch do |f| %>
    <p>
      Название события:<br>
      <%= f.text_field :event_name %>
    </p>
    <p>
      Дата/время:<br>
      <%= f.datetime_select :event_data %>
    </p>
    <p>
      Повторять событие:<br>
      <%= f.select(:period, [['Не повторять', 0], ['Каждый день', 1], ['Каждую неделю', 2],['Каждый месяц', 3], ['Каждый год', 4]]) %>
    </p>

    <p>
      <%= f.submit %>
    </p>
    <%= link_to 'Back', events_path %>
        <td><%= link_to 'Destroy', event_path(@events),
                        method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>
  </div>
    <div class="clearfix visible-xs-block"></div>
    <div class="col-xs-6 col-sm-4"></div>
  </div>

app/views/events/index.html.erb
</section>
<div class="row">
  <div class="col-md-4">
    <select id="event_type" class="form-control">
    <option value=false>Только мои</option>
    <option value=true>Посмотреть все события</option>
    </select>
  </div>
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <%= link_to 'Новое событие', new_event_path, :class => 'btn btn-success', :style => 'float:right' %>
  </div>
</div>
</section>


<div id='calendar' style = 'margin-top:20px;'></div>

<script language="JavaScript">
    $(document).ready(function() {


        // page is now ready, initialize the calendar...

        $('#calendar').fullCalendar({

            header: {
                left: 'prev,next today',
                center: 'title',

            },
            events: {
                url: '/events/list',
                data: function(){
                    return {'all_events': $('#event_type').val() };
                }
            },
            eventClick: function(calEvent, jsEvent, view) {
                window.location.href = '/events/' + calEvent.id + '/edit'
            }

        });

        $('#event_type').change(function(){
            $('#calendar').fullCalendar('refetchEvents');
        });

    });
</script>

app/views/events/new.html.erb
<%= form_for :events, url: events_path do |f| %>
    <p>
      Названия<br>
      <%= f.text_field :event_name %>
    </p>
    <p>
      Дата и время события<br>
      <%= f.datetime_select :event_data %>
    </p>
    <p>
      Повторять событие:<br>
      <%= f.select(:period, [['Не повторять', 0], ['Каждый день', 1], ['Каждую неделю', 2],['Каждый месяц', 3], ['Каждый год', 4]]) %>
    </p>
    <input id="events_false" name="events[user]" value="<%= current_user.id %>" type="hidden">


    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/events/show.html.erb
<p>
  <strong>Название:</strong>
  <%= @events.event_name %>
</p>
<p>
  <strong>Дата:</strong>
  <%= @events.event_data %>
</p>
<p>
  <strong>Повтор:</strong>
  <%= @events.period %>
</p>

<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calendar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<p></p>
<nav class="navbar navbar-inverse" role="navigation">
  <div class="row">
    <% if user_signed_in? %>
    <div class="col-md-8"><%= current_user.email %></div>
    <div class="col-md-4">
      <p class="navbar-text navbar-right"><span style='margin:1px 2px;'><%= link_to 'Изменить профиль', edit_user_registration_path  %></span>
       <span style='margin:1px 21px;'><%= link_to "Выйти", destroy_user_session_path, method: :delete  %></span></p>
    <% else %>
        <p class="navbar-text navbar-right"><span style='margin:1px 45px;'><%= link_to "Зарегистрироваться", new_user_registration_path ,:class => 'btn btn-success'  %></span>
         </p>
    <% end %>


    </div>
  </div>
</nav>

<%= yield %>
</div>
</body>
</html>